default_install_hook_types:
  - pre-push
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.28
    hooks:
      - id: uv-sync
        stages: [post-checkout, post-merge, post-rewrite]
      - id: uv-lock
        stages: [pre-push]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-check
        stages: [pre-push]
      - id: ruff-format
        stages: [pre-push]
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check
        args: ["--python", ".venv/"]
        language: python
        types: [python]
        pass_filenames: true
        stages: [pre-push]
        additional_dependencies: ["uv==0.9.30"]
